Create simple REST API for user, add postman collection
alialo2001/Budgetify pull request #1
Opened 2022-03-05 19:26 UTC by alialo2001

Hello dear mentor! I have created a simple REST API for "user" clients. The app is simple and not connected to a database, but has needed endpoints for users. Please let me know if I need to extend the app at this stage. Thank you and have a wonderful day.

2022-03-06 13:45 UTC, AudriusBaltusis requested changes

2022-03-06 13:45 UTC, AudriusBaltusis commented on package.json
> +  "description": "��#\u0000 \u0000B\u0000u\u0000d\u0000g\u0000e\u0000t\u0000i\u0000f\u0000y\u0000\r\u0000 \u0000\r\u0000 \u0000#\u0000#\u0000 \u0000T\u0000h\u0000e\u0000 \u0000a\u0000p\u0000p\u0000 \
Please fix description

2022-03-06 13:45 UTC, AudriusBaltusis commented on routes/user.js
> +router.route('/expenses')
API looks incomplete. At least you should create CRUD for `users`, `expenses`, `incomes`, `categories` and so on.

2022-03-08 19:15 UTC, alialo2001 commented
I extended the REST API. 

I plan to perform refactoring for the next homework.

2022-03-09 07:52 UTC, AudriusBaltusis approved these changes
Some refactoring is required. Please do it in second iteration

2022-03-09 07:52 UTC, AudriusBaltusis commented on public/js/user_repository.js
> +  createExpense(userId, expense, callback) {
Please create separate modules for `income`, `incomeCategory`, `user` and so on

2022-03-09 08:50 UTC, alialo2001 commented on public/js/user_repository.js
> +  createExpense(userId, expense, callback) {
Got it. Thank you!

2022-03-09 08:50 UTC, merged