Header navigation, main layout FE and accounts reading lecture10
alialo2001/Budgetify pull request #7
Opened 2022-04-17 17:50 UTC by alialo2001

Hello, dear mentors. I hope you are doing well! This pull request contains the implementation of the main page.

The project structure is getting messy. I wanted to ask, should I create a separate module for the  `accounts` page and store `account` and `accounts-list` components inside of it, or keep everything in the app folder? 

_Below is the current main page of a non-admin user with URL `http://localhost:4200/accounts`_

![image](https://user-images.githubusercontent.com/72757701/163726109-94c4edec-29fc-415c-b0a7-63b76a9788f1.png)

Thank you for checking my code and have a wonderful day!

2022-04-18 14:56 UTC, AudriusBaltusis commented
> 

Please create separate folders

2022-04-18 14:58 UTC, AudriusBaltusis commented
Please describe what was done in this PR and what HW number it is

2022-04-18 15:17 UTC, alialo2001 commented
This is the HW, where I must add the `header` and the `main page`, and I believe it is HW7. HW8 requires `static pages` and separating logic between pages, which I don't have yet.

2022-04-18 15:20 UTC, alialo2001 commented
The PR contains the implementation of the `account`, `accounts-list`, `header` and UI of the main page in general.

2022-04-19 10:47 UTC, alialo2001 commented
The HW7 is done. 

The pull request now contains:

1.    Header (with navigation)
2.  Main page UI
3. Accounts and Transactions reading from the back-end server
4. Logic separation (this is a part of the next HW, this is why the next PR will have fewer changes in the project)

2022-04-19 17:02 UTC, AudriusBaltusis requested changes

2022-04-19 17:02 UTC, AudriusBaltusis commented on client/src/app/transactions/transactions-list/transactions-list.component.ts
> +    this.transactionSub = userData.setTransactions().subscribe(() => {
Please unsubscribe or use `.pipe(take(1))`

2022-04-19 21:11 UTC, alialo2001 commented on client/src/app/services/user.service.ts
> +  setAccount() {
Thank you for the suggestion!

2022-04-20 11:09 UTC, alialo2001 commented
Dear Audrius, thank you again for the suggestions. 

I encountered one issue, which I couldn't fix: when I don't store `userId` in the `localStorage` and refresh the page, I lose all the data on the page (for example name in the header becomes `undefined undefined`). This is why I only implemented a helper service for the `accountId` right now. 

In addition, yesterday while I was waiting for your approval, I made some changes to the project in a different branch, but when I moved to this branch, they somehow became one branch, this is why this branch now contains HW for the next homework too, but it is not done yet. I will request your review again when I complete the following homework too. 

My apologies for all the inconvenience, and thank you for your valuable time!

2022-04-21 13:02 UTC, AudriusBaltusis commented
Please hurry up, Friday is deadline for all HW

2022-04-21 21:56 UTC, alialo2001 commented
HW7 and HW8 are done; only the testing homework is left if approve these two HWs of course.

2022-04-22 09:39 UTC, AudriusBaltusis approved these changes

2022-04-22 09:46 UTC, merged